### ISSUE TITLE
Cannot create workspaces

### ISSUE THREAD

**Issue by lukees** [meetalva/alva#241]
I'm unable to create a new workspace in Avla and thus can't open an existing one either.

Gif of me trying and failing: https://cl.ly/45340c1W311b

**System**
MacBook (Retina, 12-inch, Early 2015)
MacOS 10.13.3 (17D47)
Alva 0.6.1

**Comment by LKuechler** [comment]
Hi @lukees,
thanks for taking your time and creating this issue.
I could not reproduce this bug with the same MacOS version.

Could you do one more thing for me?
Please open the devtools (CMD+OPT+I), then reproduce the bug and then copy the text from inside the console tab in here.

**Comment by lukees** [comment]
Here's what happened when I…

1. opened the app
2. hit create workspace
3. created new folder called "Test" from the open file dialog that appeared
4. selected the new folder
5. hit open existing workspace (which opened the open file dialog to the "Test" folder contents with the designkit folder)
6. CMD-Up'd and selected the "Test" folder and hit Enter

https://cl.ly/2Z3N400e2R34

`/Applications/Alva.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development…:15374 Download the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
store.ts:106 Failed to open last styleguide or page: Error: ENOENT: no such file or directory, scandir '/Users/lukees/Documents/Alva/designkit/lib/patterns'
Store @ store.ts:106
electron.html:8 auto-updater message: Update not available.
app.tsx:167 Design kit path is: /Applications/Alva.app/Contents/Resources/app.asar.unpacked/build/designkit
fs.js:584 Uncaught Error: ENOENT: no such file or directory, open '/Users/lukees/Documents/Alva/designkit/alva/projects.yaml'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at Function.saveYaml (/Applications/Alva.app/Contents/Resources/app.asar/build/store/json.js:32:19)
    at Store.save (/Applications/Alva.app/Contents/Resources/app.asar/build/store/store.js:343:26)
    at Store.openStyleguide (/Applications/Alva.app/Contents/Resources/app.asar/build/store/store.js:243:14)
    at dialog.showOpenDialog.filePaths (/Applications/Alva.app/Contents/Resources/app.asar/build/component/app.js:127:19)
    at CallbacksRegistry.apply (/Applications/Alva.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:48:25)
    at EventEmitter.<anonymous> (/Applications/Alva.app/Contents/Resources/electron.asar/renderer/api/remote.js:299:21)
    at emitThree (events.js:116:13)
fs.openSync @ fs.js:584
module.(anonymous function) @ ELECTRON_ASAR.js:173
fs.writeFileSync @ fs.js:1326
saveYaml @ json.ts:59
save @ store.ts:432
openStyleguide @ store.ts:312
dialog.showOpenDialog.filePaths @ app.tsx:174
apply @ /Applications/Alva.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:48
(anonymous) @ /Applications/Alva.app/Contents/Resources/electron.asar/renderer/api/remote.js:299
emitThree @ events.js:116
emit @ events.js:197
fs.js:584 Uncaught Error: ENOENT: no such file or directory, open '/Users/lukees/Documents/Alva/designkit/alva/projects.yaml'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at Function.saveYaml (/Applications/Alva.app/Contents/Resources/app.asar/build/store/json.js:32:19)
    at Store.save (/Applications/Alva.app/Contents/Resources/app.asar/build/store/store.js:343:26)
    at Store.openStyleguide (/Applications/Alva.app/Contents/Resources/app.asar/build/store/store.js:243:14)
    at dialog.showOpenDialog.filePaths (/Applications/Alva.app/Contents/Resources/app.asar/build/component/app.js:133:19)
    at CallbacksRegistry.apply (/Applications/Alva.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:48:25)
    at EventEmitter.<anonymous> (/Applications/Alva.app/Contents/Resources/electron.asar/renderer/api/remote.js:299:21)
    at emitThree (events.js:116:13)`

**Comment by lukees** [comment]
For additional colour, I was able to download and use Alva briefly in the past.

**Comment by LKuechler** [comment]
I think i know what the bug is. You probably created, on your first use, the designkit folder inside Documents and then deleted it. Is that correct?

If yes then please open the terminal and write this command: `rm ~/.alva-prefs.yaml`
It will remove the alva user config file.

**Comment by lukees** [comment]
Yup that worked, thanks!

**Comment by LKuechler** [comment]
With these steps i can reproduce the bug.

1. Create new alva space (designkit)
2. Close Alva and delete the created space
3. Open alva an try to create a new space

I will create a new issue for this.
Thanks again for reporting and your help :)
