### ISSUE TITLE
Alva crashes on child property removal

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#583]
**Describe the bug**
When I remove a `children?: React.ReactNode` property from a component, Alva crashes on Library update. Alva only shows a grey background and throws an error in the console.

**To Reproduce**
1. Create a component that has a `children?: React.ReactNode` property
2. Connect the library with the component inside Alva
3. Remove the children-property
4. Update Library inside Alva

**Expected behavior**
Should not break.

**Device (please complete the following information):**
 - OS & Version: macOS 10.13.4
 - Version of Alva: Current Master

<details>
<summary>Console Log</summary>

```/Users/tilman/Git/alva/alva/node_modules/react-dom/cjs/react-dom.development.js:9627 The above error occurred in the <ElementContainer> component:
    in ElementContainer (created by inject-ElementContainer-with-store)
    in inject-ElementContainer-with-store (created by ElementContentContainer)
    in div (created by ElementContentContainer)
    in ElementContentContainer (created by ElementContainer)
    in Unknown (created by ElementContainer)
    in div
    in Unknown (created by Styled(Component))
    in Styled(Component) (created by Element)
    in div (created by styled.div)
    in styled.div (created by Element)
    in Element (created by ElementContainer)
    in ElementContainer (created by inject-ElementContainer-with-store)
    in inject-ElementContainer-with-store (created by ElementList)
    in div (created by styled.div)
    in styled.div (created by ElementList)
    in ElementList (created by inject-ElementList-with-store)
    in inject-ElementList-with-store (created by App)
    in div (created by styled.div)
    in styled.div
    in Unknown (created by App)
    in div (created by styled.div)
    in styled.div (created by Styled(styled.div))
    in Styled(styled.div)
    in Unknown (created by App)
    in div (created by Resizable)
    in Resizable (created by App)
    in div (created by styled.div)
    in styled.div (created by Styled(styled.div))
    in Styled(styled.div)
    in Unknown (created by App)
    in div (created by styled.div)
    in styled.div
    in Unknown (created by App)
    in App (created by inject-App-with-store)
    in inject-App-with-store
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ /Users/tilman/Git/alva/alva/node_modules/react-dom/cjs/react-dom.development.js:9627
/Users/tilman/Git/alva/alva/node_modules/react-dom/cjs/react-dom.development.js:12404 Uncaught TypeError: Cannot read property 'getType' of undefined
    at ElementContent.getSlotType (/Users/tilman/Git/alva/alva/build/model/element/element-content.js:107:30)
    at lodash_1.partition (/Users/tilman/Git/alva/alva/build/container/element-list/element-container.js:24:98)
    at arrayAggregator (/Users/tilman/Git/alva/alva/node_modules/lodash/lodash.js:489:34)
    at Function.partition (/Users/tilman/Git/alva/alva/node_modules/lodash/lodash.js:4835:16)
    at ElementContainer.render (/Users/tilman/Git/alva/alva/build/container/element-list/element-container.js:24:57)
    at Object.allowStateChanges (/Users/tilman/Git/alva/alva/node_modules/mobx/lib/mobx.js:973:15)
    at /Users/tilman/Git/alva/alva/node_modules/mobx-react/index.js:784:45
    at trackDerivedFunction (/Users/tilman/Git/alva/alva/node_modules/mobx/lib/mobx.js:3123:20)
    at Reaction.track (/Users/tilman/Git/alva/alva/node_modules/mobx/lib/mobx.js:3333:22)
    at ElementContainer.reactiveRender [as render] (/Users/tilman/Git/alva/alva/node_modules/mobx-react/index.js:779:22)
```
</details>

**Comment by marionebl** [comment]
As of bf94443ed84a5ec85112ab4c19038e8af5b428fc this does not happen anymore
