### ISSUE TITLE
`npm run build:electron` is throwing an error

### ISSUE THREAD

**Issue by gunar** [meetalva/alva#637]
**Describe the bug**
When I run `npm run build:electron` although it works (it builds) I get an error nonetheless

**To Reproduce**
1. Clone repo
2. npm install
3. npm run build:electron

**Expected behavior**
Builds without errors

**Screenshots**

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/gcg/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/home/gcg/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:electron' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prebuild:electron', 'build:electron', 'postbuild:electron' ]
5 info lifecycle meetalva@0.8.0~prebuild:electron: meetalva@0.8.0
6 info lifecycle meetalva@0.8.0~build:electron: meetalva@0.8.0
7 verbose lifecycle meetalva@0.8.0~build:electron: unsafe-perm in lifecycle true
8 verbose lifecycle meetalva@0.8.0~build:electron: PATH: /home/gcg/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/tmp/11296/alva/node_modules/.bin:/home/gcg/.nvm/versions/node/v8.9.4/bin:/home/gcg/.gem/ruby/2.3.0/bin:/opt/android-sdk-linux/tools:/opt/android-sdk-linux/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:./node_modules/.bin:../node_modules/.bin:../../node_modules/.bin:../../../node_modules/.bin:../../../../node_modules/.bin:/home/gcg/.config/yarn/global/node_modules/.bin
9 verbose lifecycle meetalva@0.8.0~build:electron: CWD: /tmp/11296/alva
10 silly lifecycle meetalva@0.8.0~build:electron: Args: [ '-c',
10 silly lifecycle   'electron-builder -mwl && node ./scripts/dist-postprocess.js' ]
11 silly lifecycle meetalva@0.8.0~build:electron: Returned: code: 1  signal: null
12 info lifecycle meetalva@0.8.0~build:electron: Failed to exec build:electron script
13 verbose stack Error: meetalva@0.8.0 build:electron: `electron-builder -mwl && node ./scripts/dist-postprocess.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/gcg/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/gcg/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid meetalva@0.8.0
15 verbose cwd /tmp/11296/alva
16 verbose Linux 4.15.18-3-MANJARO
17 verbose argv "/home/gcg/.nvm/versions/node/v8.9.4/bin/node" "/home/gcg/.nvm/versions/node/v8.9.4/bin/npm" "run" "build:electron"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error meetalva@0.8.0 build:electron: `electron-builder -mwl && node ./scripts/dist-postprocess.js`
22 error Exit status 1
23 error Failed at the meetalva@0.8.0 build:electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Device (please complete the following information):**
 - OS & Version: Linux zeno 4.15.18-3-MANJARO #1 SMP PREEMPT Fri Jun 8 06:18:41 UTC 2018 x86_64 GNU/Linux
 - Version of Alva 0.8.0

**Comment by gunar** [comment]
Same problem with `git checkout v0.8.0`

(https://github.com/meetalva/alva/issues/633)

**Comment by gunar** [comment]
Looking at the error log again, why is it trying to build the Mac image? 🤔

**Comment by gunar** [comment]
Solution: `npm run build` need to be executed before `npm run build:electron`
