### ISSUE TITLE
New bug report

### ISSUE THREAD

**Issue by tzkmx** [meetalva/alva#683]
Hey there, I just encountered the following error with Alva 2.0.10:

```
end of the stream or a document separator is expected at line 1, column 13:
    "use strict";
                ^
```

<details><summary>Stack Trace</summary>

```
YAMLException: end of the stream or a document separator is expected at line 1, column 13:
    "use strict";
                ^
    at generateError (/home/tzk/Descargas/alva-0.8.0/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/home/tzk/Descargas/alva-0.8.0/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readDocument (/home/tzk/Descargas/alva-0.8.0/node_modules/js-yaml/lib/js-yaml/loader.js:1512:5)
    at loadDocuments (/home/tzk/Descargas/alva-0.8.0/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at Object.load (/home/tzk/Descargas/alva-0.8.0/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Fs.readFile (/home/tzk/Descargas/alva-0.8.0/build/persistence/persistence.js:35:40)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

</details>

**Comment by marionebl** [comment]
Thanks for the report @tzkmx. 

What is the command you use to start Alva?

**Comment by marionebl** [comment]
@tzkmx Could you provide some more details? That would help us to address the issue.

**Comment by marionebl** [comment]
Closing for now. Feel free to ask for help on our [Gitter Org](https://gitter.im/meetalva/Lobby)
