### ISSUE TITLE
ENOENT Not Found in /usr/share/alva.asar When Building With MakePKG

### ISSUE THREAD

**Issue by ReasonablySelenium** [meetalva/alva#684]
Hey there, I just encountered the following error with Alva 0.8.0:

```
ENOENT,  not found in /usr/share/alva.asar
```

<details><summary>Stack Trace</summary>

```
Error: ENOENT,  not found in /usr/share/alva.asar
    at notFoundError (ELECTRON_ASAR.js:108:19)
    at Object.fs.readFile (ELECTRON_ASAR.js:511:16)
    at resolve (/usr/share/alva.asar/build/persistence/persistence.js:25:16)
    at new Promise (<anonymous>)
    at Function.read (/usr/share/alva.asar/build/persistence/persistence.js:24:16)
    at fileMessageHandler (/usr/share/alva.asar/build/electron/create-file-message-handler.js:65:71)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

</details>

**Comment by marionebl** [comment]
Thanks for the report @tzkmx.

Could you provide some more details?

* What is the process you use to create an Alva build?
* What steps do you follow to create a MakePKG build?
* What is the command you use to start Alva?

**Comment by marionebl** [comment]
There is now [alva-appimage](https://aur.archlinux.org/packages/alva-appimage/), an AUR that tracks our `.appimage` release builds.

```
yaourt -S alva-appimage
```

See #638 for discussion on the way forward with `alva-git`. If you run in further problem don't hesitate to hop on our gitter channel: https://gitter.im/meetalva/Lobby
