### ISSUE TITLE
New bug report

### ISSUE THREAD

**Issue by AndrewHacken** [meetalva/alva#695]
Hey there, I just encountered the following error with Alva 0.8.0:

```
ENOENT: no such file or directory, open '/Users/kat/designkit/lib/index.d.ts'
```

<details><summary>Stack Trace</summary>

```
Error: ENOENT: no such file or directory, open '/Users/kat/designkit/lib/index.d.ts'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at Function.precinct.paperwork (/Applications/Alva.app/Contents/Resources/app.asar/node_modules/precinct/index.js:140:20)
    at getImportsFromPath (/Applications/Alva.app/Contents/Resources/app.asar/src/analyzer/typescript-react-analyzer/typescript-react-analyzer.ts:242:4)
    at findPatternCandidates (/Applications/Alva.app/Contents/Resources/app.asar/src/analyzer/typescript-react-analyzer/typescript-react-analyzer.ts:209:27)
    at analyzePatterns (/Applications/Alva.app/Contents/Resources/app.asar/src/analyzer/typescript-react-analyzer/typescript-react-analyzer.ts:92:34)
    at Object.analyze (/Applications/Alva.app/Contents/Resources/app.asar/src/analyzer/typescript-react-analyzer/typescript-react-analyzer.ts:58:26)
    at <anonymous>
```

</details>

**Comment by marionebl** [comment]
Closing for now. Feel free to ask for help on our [Gitter Org](https://gitter.im/meetalva/Lobby) if the problem persists.
