### ISSUE TITLE
Cannot import library with tsx files imports css file  to Alva

### ISSUE THREAD

**Issue by anilkk** [meetalva/alva#722]
@marionebl 
Hey there, I just encountered the following error with Alva:
```
Cannot find module './button.css' from '/Users/anil/project/design-code/meetalva/patternplate/examples/webpack-react-scss/lib/button'
```

<details><summary>Stack Trace</summary>

```
Error: Cannot find module './button.css' from '/Users/anil/project/design-code/meetalva/patternplate/examples/webpack-react-scss/lib/button'
    at Function.module.exports [as sync] (/Applications/Alva.app/Contents/Resources/app.asar/node_modules/resolve/lib/sync.js:43:15)
    at precinct.paperwork.filter.map (/Applications/Alva.app/Contents/Resources/app.asar/build/analyzer/typescript-react-analyzer/typescript-react-analyzer.js:189:29)
    at Array.map (<anonymous>)
    at getImportsFromPath (/Applications/Alva.app/Contents/Resources/app.asar/build/analyzer/typescript-react-analyzer/typescript-react-analyzer.js:189:10)
    at dependencyList.reduce (/Applications/Alva.app/Contents/Resources/app.asar/build/analyzer/typescript-react-analyzer/typescript-react-analyzer.js:201:9)
    at Array.reduce (<anonymous>)
    at getImportsFromPath (/Applications/Alva.app/Contents/Resources/app.asar/build/analyzer/typescript-react-analyzer/typescript-react-analyzer.js:196:27)
    at findPatternCandidates (/Applications/Alva.app/Contents/Resources/app.asar/build/analyzer/typescript-react-analyzer/typescript-react-analyzer.js:161:30)
    at analyzePatterns (/Applications/Alva.app/Contents/Resources/app.asar/build/analyzer/typescript-react-analyzer/typescript-react-analyzer.js:56:37)
    at Object.analyze (/Applications/Alva.app/Contents/Resources/app.asar/build/analyzer/typescript-react-analyzer/typescript-react-analyzer.js:28:32)
```

</details>

## Steps to reproduce 

1. Checkout this repo - https://github.com/anilkk/patternplate/tree/alva-webpack-react-scss (wit branch name alva-webpack-react-scss)
2. Run `npm install` and `npm run build` in the project folder **examples/webpack-react-scss**.
3. Connect webpack-react-scss library to Alva. You get above error. 

But this previous commit version works fine, it doesn't use any css import. https://github.com/anilkk/patternplate/commit/043afc5813af3a874945c1680fa2954490300523

**Comment by tilmx** [comment]
Hey @anilkk,

thanks for your bug report!
Currently we do not support CSS imports directly or via Webpack – but you could load the CSS via react-helmet: https://github.com/nfl/react-helmet

The CSS Support is on our roadmap and might be covered quite soon!

Cheers,
Tilman

**Comment by anilkk** [comment]
@tilmx Awesome! Thanks for the workaround solution. It works fine.
