### ISSUE TITLE
New bug report

### ISSUE THREAD

**Issue by WLCPereira** [meetalva/alva#734]
Hey there, I just encountered the following error with Alva:

```
Cannot find module 'meetalva-loader' from '/opt/Alva/resources/app.asar'
```

<details><summary>Stack Trace</summary>

```
Error: Cannot find module 'meetalva-loader' from '/opt/Alva/resources/app.asar'
    at Function.module.exports.module.exports [as sync] (/opt/Alva/resources/app.asar/index.js:239255:15)
    at Object.createCompiler (/opt/Alva/resources/app.asar/index.js:174691:32)
    at createPatternCompiler (/opt/Alva/resources/app.asar/index.js:171784:23)
    at getBundle (/opt/Alva/resources/app.asar/index.js:171720:36)
    at Object.analyze (/opt/Alva/resources/app.asar/index.js:171742:31)
```

</details>

**Comment by marionebl** [comment]
Can reproduce, will fix today for Canary Releases.
