### ISSUE TITLE
New bug report

### ISSUE THREAD

**Issue by hustlelikeaboss** [meetalva/alva#783]
Hey there, I just encountered the following error with Alva when trying to connect to the Material UI library:

```
The "path" argument must be of type string. Received type object
```

<details><summary>Stack Trace</summary>

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.dirname (path.js:1268:5)
    at Object.analyze (/Applications/Alva Canary.app/Contents/Resources/app.asar/index.js:206125:47)
    at /Applications/Alva Canary.app/Contents/Resources/app.asar/index.js:82376:47
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by yuzl** [comment]
Hey @hustlelikeaboss we are still working on properly implementing the material library. Thanks for your feedback!

Cheers
Yuri

**Comment by tilmx** [comment]
Hey @hustlelikeaboss!
Can you share your Alva version with us? Did you try to install the library locally or via the Library Store?
Thanks!

**Comment by yuzl** [comment]
Hey @hustlelikeaboss connecting material UI should be working by know. Does it work for you? Thank you for your feedback!

Yuri
