### ISSUE TITLE
Can't install a library witch respect defined pattern

### ISSUE THREAD

**Issue by Momar-NDIAYE** [meetalva/alva#802]
Hey there, I just encountered the following error with Alva:

```
ENOENT: no such file or directory, open 'C:\Users\A748789\ant-design\lib\index.d.ts'
```

<details><summary>Stack Trace</summary>

```
Error: ENOENT: no such file or directory, open 'C:\Users\A748789\ant-design\lib\index.d.ts'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:483:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:563:29)
    at Function.module.exports.precinct.paperwork (C:\Program Files\Alva\resources\app.asar\index.js:57787:20)
    at getImportsFromPath (C:\Program Files\Alva\resources\app.asar\index.js:170783:10)
    at findPatternCandidates (C:\Program Files\Alva\resources\app.asar\index.js:170757:30)
    at analyzePatterns (C:\Program Files\Alva\resources\app.asar\index.js:170651:37)
    at Object.analyze (C:\Program Files\Alva\resources\app.asar\index.js:170609:32)
```

</details>

**Comment by Momar-NDIAYE** [comment]
Hello I want to install antd design like a library by that don't succeed.

**Comment by yuzl** [comment]
Hey, we are still working towards compatibility with more React/TS libraries. 
We gonna keep you updated! 

Cheers,
Yuri

Referencing #761
