### ISSUE TITLE
New bug report - trying connect a library package

### ISSUE THREAD

**Issue by adreson** [meetalva/alva#809]
Hey there, I just encountered the following error with Alva:

```
request to https://registry.npmjs.org/@meetalva%2fmaterial-design failed, reason: connect ETIMEDOUT 104.16.16.35:443
```

<details><summary>Stack Trace</summary>

```
FetchError: request to https://registry.npmjs.org/@meetalva%2fmaterial-design failed, reason: connect ETIMEDOUT 104.16.16.35:443
    at ClientRequest.<anonymous> (C:\Program Files\Alva Canary\resources\app.asar\index.js:212364:14)
    at ClientRequest.emit (events.js:194:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:194:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

</details>

**Comment by Webbanditten** [comment]
Your request to npmjs.org timed out?
